// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTegSiZJp55bKXTV98MuX6
// Component: bEw8_Js6cQ
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: pTegSiZJp55bKXTV98MuX6/projectcss
import sty from "./PlasmicWhat2.module.css"; // plasmic-import: bEw8_Js6cQ/css

export type PlasmicWhat2__VariantMembers = {};
export type PlasmicWhat2__VariantsArgs = {};
type VariantPropType = keyof PlasmicWhat2__VariantsArgs;
export const PlasmicWhat2__VariantProps = new Array<VariantPropType>();

export type PlasmicWhat2__ArgsType = {};
type ArgPropType = keyof PlasmicWhat2__ArgsType;
export const PlasmicWhat2__ArgProps = new Array<ArgPropType>();

export type PlasmicWhat2__OverridesType = {
  root?: p.Flex<"a">;
};

export interface DefaultWhat2Props {
  className?: string;
}

function PlasmicWhat2__RenderFunc(props: {
  variants: PlasmicWhat2__VariantsArgs;
  args: PlasmicWhat2__ArgsType;
  overrides: PlasmicWhat2__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <a
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      href={triggers.hover_root ? ("#" as const) : undefined}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      {"What are tokenomics?"}
    </a>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicWhat2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicWhat2__VariantsArgs;
    args?: PlasmicWhat2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicWhat2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicWhat2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicWhat2__ArgProps,
          internalVariantPropNames: PlasmicWhat2__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicWhat2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWhat2";
  } else {
    func.displayName = `PlasmicWhat2.${nodeName}`;
  }
  return func;
}

export const PlasmicWhat2 = Object.assign(
  // Top-level PlasmicWhat2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicWhat2
    internalVariantProps: PlasmicWhat2__VariantProps,
    internalArgProps: PlasmicWhat2__ArgProps
  }
);

export default PlasmicWhat2;
/* prettier-ignore-end */
