// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTegSiZJp55bKXTV98MuX6
// Component: Ut1D1rxZSt
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: pTegSiZJp55bKXTV98MuX6/projectcss
import sty from "./PlasmicDkicon.module.css"; // plasmic-import: Ut1D1rxZSt/css

import GroupsvgIcon from "./icons/PlasmicIcon__Groupsvg"; // plasmic-import: RKRCCKAmyu/icon

export type PlasmicDkicon__VariantMembers = {};
export type PlasmicDkicon__VariantsArgs = {};
type VariantPropType = keyof PlasmicDkicon__VariantsArgs;
export const PlasmicDkicon__VariantProps = new Array<VariantPropType>();

export type PlasmicDkicon__ArgsType = {};
type ArgPropType = keyof PlasmicDkicon__ArgsType;
export const PlasmicDkicon__ArgProps = new Array<ArgPropType>();

export type PlasmicDkicon__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultDkiconProps {
  className?: string;
}

function PlasmicDkicon__RenderFunc(props: {
  variants: PlasmicDkicon__VariantsArgs;
  args: PlasmicDkicon__ArgsType;
  overrides: PlasmicDkicon__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <GroupsvgIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDkicon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDkicon__VariantsArgs;
    args?: PlasmicDkicon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDkicon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDkicon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDkicon__ArgProps,
          internalVariantPropNames: PlasmicDkicon__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDkicon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDkicon";
  } else {
    func.displayName = `PlasmicDkicon.${nodeName}`;
  }
  return func;
}

export const PlasmicDkicon = Object.assign(
  // Top-level PlasmicDkicon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDkicon
    internalVariantProps: PlasmicDkicon__VariantProps,
    internalArgProps: PlasmicDkicon__ArgProps
  }
);

export default PlasmicDkicon;
/* prettier-ignore-end */
