// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTegSiZJp55bKXTV98MuX6
// Component: cQ9uZKVS15
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: pTegSiZJp55bKXTV98MuX6/projectcss
import sty from "./PlasmicTwicon.module.css"; // plasmic-import: cQ9uZKVS15/css

import Vector1SvgIcon from "./icons/PlasmicIcon__Vector1Svg"; // plasmic-import: 3jP2N6sa9b/icon

export type PlasmicTwicon__VariantMembers = {};
export type PlasmicTwicon__VariantsArgs = {};
type VariantPropType = keyof PlasmicTwicon__VariantsArgs;
export const PlasmicTwicon__VariantProps = new Array<VariantPropType>();

export type PlasmicTwicon__ArgsType = {};
type ArgPropType = keyof PlasmicTwicon__ArgsType;
export const PlasmicTwicon__ArgProps = new Array<ArgPropType>();

export type PlasmicTwicon__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultTwiconProps {
  className?: string;
}

function PlasmicTwicon__RenderFunc(props: {
  variants: PlasmicTwicon__VariantsArgs;
  args: PlasmicTwicon__ArgsType;
  overrides: PlasmicTwicon__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <Vector1SvgIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTwicon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTwicon__VariantsArgs;
    args?: PlasmicTwicon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTwicon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTwicon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTwicon__ArgProps,
          internalVariantPropNames: PlasmicTwicon__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTwicon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTwicon";
  } else {
    func.displayName = `PlasmicTwicon.${nodeName}`;
  }
  return func;
}

export const PlasmicTwicon = Object.assign(
  // Top-level PlasmicTwicon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTwicon
    internalVariantProps: PlasmicTwicon__VariantProps,
    internalArgProps: PlasmicTwicon__ArgProps
  }
);

export default PlasmicTwicon;
/* prettier-ignore-end */
