// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pTegSiZJp55bKXTV98MuX6
// Component: 7L1iefD1JK
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: pTegSiZJp55bKXTV98MuX6/projectcss
import sty from "./PlasmicGiticon.module.css"; // plasmic-import: 7L1iefD1JK/css

import vector2SvgFrW2ZtSW from "./images/vector2Svg.svg"; // plasmic-import: FrW2ztS-W/picture

export type PlasmicGiticon__VariantMembers = {};
export type PlasmicGiticon__VariantsArgs = {};
type VariantPropType = keyof PlasmicGiticon__VariantsArgs;
export const PlasmicGiticon__VariantProps = new Array<VariantPropType>();

export type PlasmicGiticon__ArgsType = {};
type ArgPropType = keyof PlasmicGiticon__ArgsType;
export const PlasmicGiticon__ArgProps = new Array<ArgPropType>();

export type PlasmicGiticon__OverridesType = {
  root?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultGiticonProps {
  className?: string;
}

function PlasmicGiticon__RenderFunc(props: {
  variants: PlasmicGiticon__VariantsArgs;
  args: PlasmicGiticon__ArgsType;
  overrides: PlasmicGiticon__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <p.PlasmicImg
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      alt={""}
      className={classNames(
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
      displayHeight={"26px" as const}
      displayMaxHeight={"none" as const}
      displayMaxWidth={"100%" as const}
      displayMinHeight={"0" as const}
      displayMinWidth={"0" as const}
      displayWidth={"27px" as const}
      loading={"lazy" as const}
      src={{
        src: vector2SvgFrW2ZtSW,
        fullWidth: 156,
        fullHeight: 150,
        aspectRatio: 1.038462
      }}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicGiticon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicGiticon__VariantsArgs;
    args?: PlasmicGiticon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicGiticon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicGiticon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicGiticon__ArgProps,
          internalVariantPropNames: PlasmicGiticon__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicGiticon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicGiticon";
  } else {
    func.displayName = `PlasmicGiticon.${nodeName}`;
  }
  return func;
}

export const PlasmicGiticon = Object.assign(
  // Top-level PlasmicGiticon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicGiticon
    internalVariantProps: PlasmicGiticon__VariantProps,
    internalArgProps: PlasmicGiticon__ArgProps
  }
);

export default PlasmicGiticon;
/* prettier-ignore-end */
